version: '3'
services:

  #PHP-FPM Service
  kineo-fpm:
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    container_name: kineo-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - moodledata:/var/moodledata
    networks:
      - kineo-network
    depends_on:
      - kineo-mysql

  #Nginx Service
  kineo-nginx:
    image: nginx:alpine
    container_name: kineo-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - moodledata:/var/moodledata
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - kineo-network
    depends_on:
      - kineo-mysql

  #MySQL Service
  kineo-mysql:
    image: mysql:5.7.22
    container_name: kineo-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kineo_test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kineo-network

#Docker Networks
networks:
  kineo-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  moodledata:
    driver: local